name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: luajit-make
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        run: make init

      - name: Run tests
        run: make test
